#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Tasuku43\DependencyChecker\Console\Command\AnalyseCommand;

$app = new Application('Dependency check command', '0.1.0-dev');

$app->add(new AnalyseCommand());

$app->run();
