#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Tasuku43\DependencyChecker\Console\Command\AnalyseCommand;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$app = new Application('Dependency check command', '0.1.0');

$app->add(new AnalyseCommand());

$app->run();
